### ISSUE TITLE
Consider reverting JSON config to PHP

### ISSUE THREAD

**Issue by sbine** [BePsvPT/laravel-security-header#1]
Thanks for making this awesome open source library!

I'm in the process of upgrading an app to Laravel 5.3 and version 2.0.0 of laravel-security-header. We've run into issues because we were using conditional logic (based on `APP_ENV`) to generate distinct CSP directives and enable different features for development vs. production environments. Now that the config is in a JSON file, it's become much more difficult to conditionally define rulesets as we were previously. I believe Laravel packages traditionally use PHP config files for this reason. Would you consider reverting to a PHP config?

**Comment by BePsvPT** [comment]
2.1.0 revert the config file from json to php, after upgrading, you need to republish the config file.

**Comment by sbine** [comment]
Thanks so much! :)
